spring:
  application:
    name: fresh-market
  datasource:
    url: jdbc:mysql://mysql:3306/app_db
    username: app
    password: app1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  file:
    name: /app/logs/app.log

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
